### ISSUE TITLE
Environment variables for URLs

### ISSUE THREAD

**Issue by jmezo** [zgendao/balancy#8]
Currently when we pass in web3 or database URLs to the CLI commands we have to pass them to every function that uses these connections. Instead of this we could use python environment variables. There are three things I'd like to implement related to this issue:
* When using the `--w3url` or `--db-uri` flags save their values to python env variables, so they can be accessed globally.
* Set a default value for these flags inside a `.env` file that can be overridden with the flags.
*  Add `set-defaults` command that will save the new values in a `.env` file as defaults if used with  `--w3url` or `--db-uri`.

**Comment by PumpkinSeed** [comment]
Not finished properly. See the requested changes on the #10.
